In [33]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


In [34]:
import pandas as pd 
import csv
import numpy as np

In [35]:
# df = pd.read_csv("/content/drive/My Drive/newreviews.csv") 
# برای اجرای مجدد لطفا دیتاست پیوست با نام زیر را آپلود کرده و سپس ادامه کد را اجزا کنید
df = pd.read_csv("newreviews.csv") 

In [36]:
df.head()

reviewId  ... totalScore
0  gp:AOqpTOH2VEhd1ldAR1zxGzjJEIa37fCBgY9S3sqe_TE...  ...    4.43388
1  gp:AOqpTOH5OkwJH-nRT4nopD_JNTIYpWs1xWzOsFE-pn7...  ...    4.43388
2  gp:AOqpTOEaw6IQ_8TizWQrZCvwfKfhYqJ0n6GxwFuQF7u...  ...    4.43388
3  gp:AOqpTOG4LKg25ejg1Hw1TWs6_gIXhpwJRZZpXssMygx...  ...    4.43388
4  gp:AOqpTOGQ7NShvSVr9Vqz67MSeTN_3rkBuYtQRtsyAo5...  ...    4.43388

[5 rows x 13 columns]

In [37]:
# ابتدا ستون‌های عددی را جدا کرده و در آرایه‌های زیر قرار می‌دهیم
prev_data = df.select_dtypes(include=np.number)
a = prev_data["score"].to_numpy()
b = prev_data["thumbsUpCount"].to_numpy()
c = prev_data["totalScore"].to_numpy()
print(a)
print(b)
print(c)

[1 1 1 ... 5 5 5]
[81  9 57 ...  0  0  0]
[4.43388   4.43388   4.43388   ... 4.3803525 4.3803525 4.3803525]


In [38]:
# برای محاسبه میانگین از تابع زیر استفاده می‌کنیم
def mean(feature):
  means = 0
  for x in feature:
    means = means + x
  means/=len(feature)
  return means

In [39]:
# میانگین هر ستون از داده را محاسبه می‌کنیم
aa = mean(a)
bb = mean(b)
cc = mean(c)
print(aa)
print(bb)
print(cc)

3.047356828193833
5.343795888399413
4.4912845634364125


In [40]:
# میانگین داده‌ها را از مقدار آنها کم می‌کنیم
a = a-aa
b = b-bb
c = c-cc
print(a)
print(b)
print(c)

[-2.04735683 -2.04735683 -2.04735683 ...  1.95264317  1.95264317
  1.95264317]
[75.65620411  3.65620411 51.65620411 ... -5.34379589 -5.34379589
 -5.34379589]
[-0.05740456 -0.05740456 -0.05740456 ... -0.11093206 -0.11093206
 -0.11093206]


In [41]:
# داده‌های جدید را کنار هم قرار می‌دهیم
prev_data = pd.DataFrame(a,columns=["1"])
prev_data["2"] = b
prev_data["3"] = c

In [42]:
# داده هارا کنار هم گذاشته، ماتریس کو-واریانس را محاسبه می‌کنیم
CO = np.cov(prev_data.to_numpy().T)
print (CO)

[[ 1.73807415e+00 -8.22988314e-01 -7.34591495e-03]
 [-8.22988314e-01  4.01634535e+02 -7.78727107e-02]
 [-7.34591495e-03 -7.78727107e-02  2.88884872e-02]]


In [43]:
# بردار و مقدار ویژه ها را محاسبه می‌کنیم
w, v = np.linalg.eig(CO)

In [44]:
# مقدارهای ویژه به صورت زیر هستند، مقدار اول از همه بزرگتر و مقدار سوم از همه کوچکتر است
print(w)

[4.01636244e+02 1.73641344e+00 2.88403971e-02]


In [45]:
# بین مقادیر ویژه درصد گیری می‌کنیم و می‌توانیم با تعیین کردن یک حد مرزی، بردارهایی با مقدار ویژه زیر آن حد را حذف کنیم
# مثلا در اینجا مقدار سوم از همه کمتر است و آن را در نهایت حذف خواهیم کرد
sum_of_w = np.sum(w)
w = (w/sum_of_w)*100
print(w)

[9.95624077e+01 4.30442983e-01 7.14930342e-03]


In [46]:
# بردارهای ویژه به صورت زیر هستند
print(v)

[[ 2.05798674e-03 -9.99988222e-01  4.39544062e-03]
 [-9.99997864e-01 -2.05711470e-03  2.02908858e-04]
 [ 1.93864543e-04  4.39584881e-03  9.99990319e-01]]


In [47]:
# با ضرب بردارهای ویژه در مقادیر قبلی به مقادیر جدیدی می‌رسیم
new_data = prev_data.dot(v.T)

In [48]:
# از داده‌های جدید ایجاد شده سه ستون ایجاد می‌کنیم
new_1 = new_data[0]
new_2 = new_data[1]
new_3 = new_data[2]

In [49]:
# ستون‌های مربوط به داده قبلی را حذف می‌کنیم
df.drop('score',inplace=True, axis=1)
df.drop('thumbsUpCount', inplace=True, axis=1)
df.drop('totalScore', inplace=True, axis=1)

In [50]:
df.head()

reviewId  ...      appId
0  gp:AOqpTOH2VEhd1ldAR1zxGzjJEIa37fCBgY9S3sqe_TE...  ...  com.anydo
1  gp:AOqpTOH5OkwJH-nRT4nopD_JNTIYpWs1xWzOsFE-pn7...  ...  com.anydo
2  gp:AOqpTOEaw6IQ_8TizWQrZCvwfKfhYqJ0n6GxwFuQF7u...  ...  com.anydo
3  gp:AOqpTOG4LKg25ejg1Hw1TWs6_gIXhpwJRZZpXssMygx...  ...  com.anydo
4  gp:AOqpTOGQ7NShvSVr9Vqz67MSeTN_3rkBuYtQRtsyAo5...  ...  com.anydo

[5 rows x 10 columns]

In [51]:
# به تعداد دلخواه از ستون‌های ایجاد شده با توجه به نتایج قبلی صرف نظر کرده و بقیه را اضافه می‌کنیم
# در اینجا دو ستون از سه ستون ایجاد شده را اضافه می‌کنیم
df['new_feature_1'] = new_1
df['new_feature_2'] = new_2

In [52]:
df.head()

reviewId  ... new_feature_2
0  gp:AOqpTOH2VEhd1ldAR1zxGzjJEIa37fCBgY9S3sqe_TE...  ...      1.891707
1  gp:AOqpTOH5OkwJH-nRT4nopD_JNTIYpWs1xWzOsFE-pn7...  ...      2.039820
2  gp:AOqpTOEaw6IQ_8TizWQrZCvwfKfhYqJ0n6GxwFuQF7u...  ...      1.941078
3  gp:AOqpTOG4LKg25ejg1Hw1TWs6_gIXhpwJRZZpXssMygx...  ...      2.033648
4  gp:AOqpTOGQ7NShvSVr9Vqz67MSeTN_3rkBuYtQRtsyAo5...  ...      2.056276

[5 rows x 12 columns]

In [53]:
# دیتاست جدید ایجاد شده و از بخش فایل‌ها قابل دانلود است
new_df = pd.DataFrame(df)
new_df.to_csv('pcadataset.csv', index=None, header=True)

In [54]:
# # روش زیر همین کار را با استفاده از کتابخانه آماده انجام داده است
# from sklearn.decomposition import PCA
# pca = PCA(n_components=2)
# principalComponents = pca.fit_transform(prev_data)
# principalComponents